# This creates one large string
lorem_ipsum = (
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. '
    'Morbi varius neque tortor, sit amet facilisis purus consectetur sed. '
    'Donec vestibulum fringilla massa, quis imperdiet turpis laoreet ut. '
    'Fusce in nunc augue. Nam vitae vehicula augue. Nulla at finibus ex. Nam '
    'euismod, nulla a maximus consectetur, enim orci congue tortor, ac '
    'vestibulum mauris velit bibendum dolor. In quis scelerisque nisl. Nullam '
    'sollicitudin mauris erat, ac pharetra tortor sollicitudin sed. '
    'Pellentesque pharetra dolor a sapien tempus, eget fringilla ante '
    'ultricies. Ut egestas, purus eget aliquam iaculis, elit orci convallis '
    'nibh, in congue nibh lectus dignissim mauris. Donec lacinia nulla quam, '
    'eget auctor leo accumsan congue. Phasellus elementum dolor eu gravida '
    'feugiat. Vestibulum vel odio et magna pretium euismod a nec enim. '
    'Pellentesque egestas non ligula in posuere. Proin vel tincidunt felis, '
    'ac tempus erat. Suspendisse potenti. Sed venenatis metus lacus, eget '
    'vestibulum massa interdum lobortis. Ut fringilla purus nunc, nec congue '
    'ligula bibendum eu. Donec aliquam mi dui, eu feugiat tortor varius '
    'rutrum. Maecenas quis est a turpis volutpat aliquet et vulputate orci. '
    'Duis accumsan elementum augue a pulvinar. Aenean in purus sit amet lacus '
    'semper varius. Suspendisse mattis nulla a augue vehicula, a eleifend '
    'arcu scelerisque. Nam congue elit velit, venenatis elementum ante '
    'eleifend in. Integer convallis ultrices elit sed consequat. Phasellus '
    'viverra enim sed lectus porta laoreet. Phasellus ex neque, viverra vitae '
    'mi ut, suscipit sodales quam. Fusce eu accumsan erat, quis euismod '
    'nisi. Pellentesque iaculis velit rhoncus enim pellentesque, id convallis '
    'velit lobortis. Nullam sit amet sapien sed nunc convallis mollis. '
    'Curabitur nisl mi, finibus eget nisl condimentum, dictum finibus ligula.')
